name: 'Install swift tool'
description: 'Clone and build a swift tool'
author: 'Benedek Kozma'
branding:
  color: 'green'
  icon: 'download'
inputs:
  url:
    description: 'Git URL of the tool to build'
    required: true
  commit:
    description: 'Git commit hash to clone'
    required: false
  branch:
    description: 'Git branch/tag to clone, overridden by commit'
    required: false
  version:
    description: 'Version range to choose max satisfying version by, overridden by commit/branch, format: https://devhints.io/semver'
    required: false
  use-cache:
    description: 'Use cache to restore/save build product'
    required: false
    default: 'true'
runs:
  using: 'node16'
  main: 'dist/index.js'
