name: "Manual Update"

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update dependencies
      run: yarn upgrade --latest
    - name: Build
      run: make build
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update dependencies"
        branch: yarn-upgrade-latest
        delete-branch: true
        title: "Update dependencies"
        body: "Automatically created by the 'Manual Update' workflow"
