name: "Manual build"

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Commit
      uses: EndBug/add-and-commit@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
