name: "Test action"

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11.0]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: make build
    - name: Run action without branch
      uses: ./
      with:
        url: https://github.com/nicklockwood/SwiftFormat
    - name: Run action with branch
      uses: ./
      with:
        url: https://github.com/Cyberbeni/xcbeautify
        branch: linux-fixes
    - name: Run action with version
      uses: ./
      with:
        url: https://github.com/realm/SwiftLint
        version: '*'
        use-cache: ${{ runner.os == 'Linux' }}
    - name: Test tools in path
      run: |
        echo "class Test {}" > ./test.swift
        swiftformat --lint ./test.swift
        xcbeautify --version
        swiftlint lint ./test.swift
