name: "Test action"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Swift
      uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.1.2' # Install latest Swift release
    - name: Run action without branch
      uses: ./
      with:
        url: https://github.com/nicklockwood/SwiftFormat
    - name: Run action with branch
      uses: ./
      with:
        url: https://github.com/Cyberbeni/xcbeautify
        branch: linux-fixes
    - name: Test tools in path
      run: |
        which swiftformat
        which xcbeautify
