name: "Test action - extended"

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/test-extended.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: swift:5.3
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run action with version
      uses: ./
      with:
        url: https://github.com/apple/swift-format
        version: '^0.50300.0'
    - name: Test tools in path
      run: |
        echo "class Test {}" > ./test.swift
        swift-format ./test.swift
